LOG_TEMPLATES = {
    "USER_REGISTER": "User[email={email}] registered with role={role}",
    "USER_LOGIN": "User[email={email}] login attempted",
    "USER_PROFILE_READ": "User[id={user_id}] profile read",
    "USER_PROFILE_UPDATE": "User[id={user_id}] profile update nickname={nickname}",
    "MOOD_CREATE": "Mood[user_id={user_id}] create mood_level={mood_level} mood_tags={mood_tags} record_date={record_date}",
    "MOOD_LIST": "Mood[user_id={user_id}] list from={start_date} to={end_date}",
    "MOOD_UPDATE": "Mood[id={mood_id}] update mood_level={mood_level} mood_tags={mood_tags}",
    "MOOD_DELETE": "Mood[id={mood_id}] delete requested by user_id={user_id}",
    "MOOD_TREND": "Mood[user_id={user_id}] trend generated with MoodTag={mood_tags}",
    "MOOD_TODAY_GET": "Mood[user_id={user_id}] today mood requested for date={today}",
    "ASSESSMENT_LIST": "Assessment[category={category}] list requested",
    "ASSESSMENT_CREATE": "Assessment[title={title}] create category={category}",
    "ASSESSMENT_DETAIL": "Assessment[id={assessment_id}] detail read",
    "ASSESSMENT_SUBMIT": "Assessment[id={assessment_id}] submitted by user_id={user_id} score={score}",
    "ASSESSMENT_RESULT": "Assessment[id={assessment_id}] result_level={result_level} suggestion={suggestion}",
    "JOURNAL_CREATE": "Journal[user_id={user_id}] create title={title} mood_level={mood_level} mood_tags={mood_tags}",
    "JOURNAL_LIST": "Journal[user_id={user_id}] list mood_level={mood_level}",
    "JOURNAL_UPDATE": "Journal[id={journal_id}] update title={title} is_private={is_private}",
    "JOURNAL_DELETE": "Journal[id={journal_id}] delete requested by user_id={user_id}",
    "AUTH_REQUIRED": "Auth[path={path}] token required for write operation",
    "AUTH_ADMIN_REQUIRED": "Auth[user_id={user_id}] admin role required",
    "THEME_BACKEND_HINT": "Theme[name={theme}] backend hint requested for frontend theme sync",
    "ERROR_WRAPPED": "Error[code={code}] entity={entity} message={message}",
    "AUDIT_WRITE": "Audit[method={method}] path={path} actor={actor}",
    "HEALTH_CHECK": "Health[service=MindGarden] checked",
}

